const blogPosts = [
  {
    id: 1,
    title: "3 cost saving tips for businesses implementing generative AI",
    date: "January 21, 2025",
    author: "Uchenna Okpagu",
    image: "./assets/images/blog-area/blog-thumb-1.png",
    url: "https://nairametrics.com/2025/01/21/3-cost-saving-tips-for-businesses-implementing-generative-ai/",
    effect: "reveal zoom-out",
  },
  {
    id: 2,
    title: "Risks African businesses should be wary of while embarking on their AI transformation",
    date: "January 06, 2024",
    author: "Uchenna Okpagu",
    image: "./assets/images/blog-area/blog-thumb-1.png",
      url: "https://nairametrics.com/2025/01/06/risks-african-businesses-should-be-wary-of-while-embarking-on-their-ai-transformation/",
    effect: "reveal right",
  },
  {
    id: 3,
    title: "How to adopt an AI-First mindset in this digital era",
    date: "Feburary 26, 2025",
    author: "Uchenna Okpagu",
    image: "./assets/images/blog-area/blog-thumb-1.png",
    url: "https://nairametrics.com/2025/02/26/how-to-adopt-an-ai-first-mindset-in-this-digital-era/",
    effect: "reveal left",
  },
  {
    id: 4,
    title: "A simple guide for African businesses to implement AI transformation ",
    date: "January 04, 2024",
    author: "Uchenna Okpagu",
    image: "./assets/images/blog-area/blog-thumb-1.png",
    url: "https://nairametrics.com/2025/01/04/a-simple-guide-for-african-businesses-to-implement-ai-transformation/",
    effect: "reveal right",
  },
  {
    id: 5,
    title: "Maximizing customer support efficiency with AI assistants: A guide for businesses ",
    date: "Febuary 24, 2025",
    author: "Uchenna Okpagu",
    image: "./assets/images/blog-area/blog-thumb-1.png",
    url: "https://nairametrics.com/2025/02/24/maximizing-customer-support-efficiency-with-ai-assistants-a-guide-for-businesses/",
    effect: "reveal left",
  },
  {
    id: 6,
    title: "AI Workflows vs. AI Agents: Choosing the right solution to supercharge your business",
    date: "January 23, 2025",
    author: "Uchenna Okpagu",
    image: "./assets/images/blog-area/blog-thumb-1.png",
    url: "https://nairametrics.com/2025/01/23/ai-workflows-vs-ai-agents-choosing-the-right-solution-to-supercharge-your-business/",
    effect: "reveal left",
  },
  // {
  //   id: 7,
  //   title: "A simple guide for African businesses to implement AI transformation",
  //   date: "Mar 01, 2025",
  //   author: "Uchenna Okpagu",
  //   image: "/assets/images/blog8.jpg",
  //   categories: ["marketing", "branding"],
  //   url: "https://nairametrics.com/2025/01/04/a-simple-guide-for-african-businesses-to-implement-ai-transformation/",
  //   effect: "reveal left",
  // },
 

];

export default blogPosts;
