const blogPosts = [
  {
    id: 1,
    title: "3 cost saving tips for businesses implementing generative AI",
    date: "January 21, 2025",
    author: "Uche Okpagu",
    image: "/assets/images/blog-area/blog4.jpeg",
    categories: ["branding", "web-design"],
    link: "https://nairametrics.com/2025/01/21/3-cost-saving-tips-for-businesses-implementing-generative-ai/",
    effect: "reveal zoom-out",
  },
  {
    id: 2,
    title: "Risks African businesses should be wary of while embarking on their AI transformation",
    date: "January 06, 2024",
    author: "Uche Okpagu",
    image: "/assets/images/blog-area/blog5.png",
    categories: ["video", "web-design", "branding"],
    link: "https://nairametrics.com/2025/01/06/risks-african-businesses-should-be-wary-of-while-embarking-on-their-ai-transformation/",
    effect: "reveal right",
  },
  {
    id: 3,
    title: "The Role of User Experience in Portfolio Design",
    date: "October 06, 2024",
    author: "Uche Okpagu",
    image: "/assets/images/blog-area/blog-thumb-3.png",
    categories: ["video", "web-design", "marketing"],
    effect: "reveal left",
  },
  {
    id: 4,
    title: "Tips for maximizing engagement and reach",
    date: "October 06, 2024",
    author: "Uche Okpagu",
    image: "/assets/images/blog-area/blog-thumb-4.png",
    categories: ["branding", "marketing", "video"],
    effect: "reveal right",
  },
  {
    id: 5,
    title: "The role of user experience nicholls in modern web design",
    date: "October 06, 2024",
    author: "Uche Okpagu",
    image: "/assets/images/blog-area/blog-thumb-5.png",
    categories: ["marketing", "branding"],
    effect: "reveal left",
  },
];

export default blogPosts;
