const blogPosts = [
  {
    id: 1,
    title: "3 cost saving tips for businesses implementing generative AI",
    date: "January 21, 2025",
    author: "Uchenna Okpagu",
    image: "/assets/images/blog-area/blog4.jpeg",
    categories: ["branding", "web-design"],
    url: "https://nairametrics.com/2025/01/21/3-cost-saving-tips-for-businesses-implementing-generative-ai/",
    effect: "reveal zoom-out",
  },
  {
    id: 2,
    title: "Risks African businesses should be wary of while embarking on their AI transformation",
    date: "January 06, 2024",
    author: "Uchenna Okpagu",
    image: "/assets/images/blog-area/blog-5.png",
    categories: ["video", "web-design", "branding"],
    url: "https://nairametrics.com/2025/01/06/risks-african-businesses-should-be-wary-of-while-embarking-on-their-ai-transformation/",
    effect: "reveal right",
  },
  {
    id: 3,
    title: "Africa’s digital rise demands smarter identity verification ",
    date: "March 15, 2025",
    author: "Uchenna Okpagu",
    image: "/assets/images/blog6.jpg",
    categories: ["video", "web-design", "marketing"],
    url: "https://techcabal.com/2025/03/15/africa-identity-verification/",
    effect: "reveal left",
  },
  {
    id: 4,
    title: "A simple guide for African businesses to implement AI transformation ",
    date: "January 04, 2024",
    author: "Uchenna Okpagu",
    image: "/assets/images/blog-area/blog-5.png",
    categories: ["branding", "marketing", "video"],
    url: "https://nairametrics.com/2025/01/04/a-simple-guide-for-african-businesses-to-implement-ai-transformation/",
    effect: "reveal right",
  },
  {
    id: 5,
    title: "From red tape to rocket fuel: Why Africa’s policies must catch up with potential",
    date: "Feb 21, 2025",
    author: "Uchenna Okpagu",
    image: "/assets/images/blog7.jpeg",
    categories: ["marketing", "branding"],
    url: "https://techcabal.com/2025/02/21/undp-africa-policies-and-potential/",
    effect: "reveal left",
  },
  {
    id: 6,
    title: "Dear tech journalist, look beyond business updates",
    date: "Mar 01, 2025",
    author: "Uchenna Okpagu",
    image: "/assets/images/blog8.jpg",
    categories: ["marketing", "branding"],
    url: "https://techcabal.com/2025/03/01/on-tech-journalism/",
    effect: "reveal left",
  },
  {
    id: 7,
    title: "Dear tech journalist, look beyond business updates",
    date: "Mar 01, 2025",
    author: "Uchenna Okpagu",
    image: "/assets/images/blog8.jpg",
    categories: ["marketing", "branding"],
    url: "https://techcabal.com/2025/02/21/undp-africa-policies-and-potential/",
    effect: "reveal left",
  },
 

];

export default blogPosts;
